### ISSUE TITLE
真是糟糕

### ISSUE THREAD

**Issue by Horange321** [577fkj/GodMode#2]
嘿，我的伙计。它在新的lsp框架貌似无法运行，还告诉我上帝模式无法激活。我是说，有人知道怎么处理吗

**Comment by 577fkj** [comment]
真是糟糕，现在我已经不用安卓了，没办法给你解决问题。

**Comment by Horange321** [comment]
不好意思。系统框架的勾不知道什么时候没了。勾上就可以用了

**Comment by Horange321** [comment]
大佬转ios了吗？怎么放弃折腾安卓了

**Comment by 577fkj** [comment]
> 大佬转ios了吗？怎么放弃折腾安卓了

不想折腾安卓了 换苹果了
